spring.application.name=Venturepulse
spring.datasource.url=jdbc:mysql://localhost:3306/venture_pulse
spring.datasource.username=Manwani
spring.datasource.password=Gaurav123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
@org.springframework.beans.factory.annotation.Autowired(required=(true)

logging.level.root=INFO
logging.level.com.sgt.venturepulse=INFO

server.port=8081
management.endpoints.web.exposure.include=health,info
